AMOUNT_OF_FILES = 100
OUT_DIRECTORY = "output"
TEMPLATES_DIRECTORY = "base_templates"
PERCENT_DUPLICATE = 0.05
PERCENT_EXTENSION_SCRAMBLE = 0.05
PERCENT_STRUCT_CORRUPTION = 0.05 
PERCENT_CHAR_CORRUPT = 0.05

